CREATE DATABASE DB_POWERBI;

CREATE TABLE CLIENTES (
    ID SERIAL PRIMARY KEY,
    NOME TEXT,
    SOBRENOME TEXT,
    EMAIL TEXT
);

INSERT INTO CLIENTES 
    (NOME, SOBRENOME, EMAIL)
    VALUES
    ('JOÃO', 'SILVA', 'JOAO@SILVA.COM');
    
INSERT INTO CLIENTES 
    (NOME, SOBRENOME, EMAIL)
    VALUES
    ('MARIA', 'SANTOS', 'MARIA@SANTOS.COM');

INSERT INTO CLIENTES 
    (NOME, SOBRENOME, EMAIL)
    VALUES
    ('JOSÉ', 'PEREIRA', 'JOSÉ@PEREIRA.COM');

SELECT * FROM CLIENTES;

CREATE TABLE PEDIDOS (
    ID SERIAL PRIMARY KEY,
    ID_CLIENTES INT,
    DATA_PEDIDO DATE,
    TOTAL NUMERIC(6,2),
    STATUS TEXT CHECK(STATUS IN (
        'EM ANDAMENTO',
        'FINALIZADO',
        'CANCELADO')),
    FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID)
);

ALTER TABLE PEDIDOS 
    ALTER COLUMN STATUS 
    SET DEFAULT 'EM ANDAMENTO';

INSERT INTO PEDIDOS
    (ID_CLIENTES, DATA_PEDIDO,TOTAL)
    VALUES
    (1,'2024-04-01',100),
    (2,'2024-04-02',50),
    (3,'2024-04-03',150.40),
    (2,'2024-04-04',90.90),
    (1,'2024-04-05',87.99);

SELECT * FROM PEDIDOS;

INSERT INTO PEDIDOS
    (ID_CLIENTES, DATA_PEDIDO,TOTAL)
    VALUES
    (3,'2024-04-06',250.35);